import { chromium } from "playwright";
const [base = "http://localhost:3123", out = "/tmp/shots"] = process.argv.slice(2);
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 1500, height: 1100 } });
await page.goto(base, { waitUntil: "networkidle" });
await page.getByRole("button", { name: "教材3" }).click();
await page.waitForTimeout(500);
await page.getByRole("button", { name: "間取り図", exact: true }).first().click();
await page.waitForTimeout(1000);
await page.screenshot({ path: `${out}/floor2.png` });
await page.getByRole("button", { name: "立面図", exact: true }).first().click();
await page.waitForTimeout(1500);
const el = page.locator("text=日影規制（法56条の2").first();
await el.scrollIntoViewIfNeeded();
await page.waitForTimeout(300);
const box = await el.boundingBox();
await page.screenshot({ path: `${out}/shadow.png`, clip: { x: 0, y: Math.max(0, box.y - 20), width: 520, height: 700 } });
await browser.close();
console.log("done");
